// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIv2v4Hkka_6rcT-u-X9dXmAYFCDprbtQ',
    appId: '1:330337503528:web:380940e863bdca0fc6281d',
    messagingSenderId: '330337503528',
    projectId: 'commv-users',
    authDomain: 'commv-users.firebaseapp.com',
    storageBucket: 'commv-users.firebasestorage.app',
    measurementId: 'G-EE450VXRZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-DHkDXsntIlFdPfu4JbSHuEe2bJBFD-k',
    appId: '1:330337503528:android:cc6714710bf13f1ac6281d',
    messagingSenderId: '330337503528',
    projectId: 'commv-users',
    storageBucket: 'commv-users.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA73ZxhRvCWF__iG9-N4aW5MGCO4hUR7Q',
    appId: '1:330337503528:ios:713789fce0ae9617c6281d',
    messagingSenderId: '330337503528',
    projectId: 'commv-users',
    storageBucket: 'commv-users.firebasestorage.app',
    iosBundleId: 'com.commv.commv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA73ZxhRvCWF__iG9-N4aW5MGCO4hUR7Q',
    appId: '1:330337503528:ios:713789fce0ae9617c6281d',
    messagingSenderId: '330337503528',
    projectId: 'commv-users',
    storageBucket: 'commv-users.firebasestorage.app',
    iosBundleId: 'com.commv.commv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIv2v4Hkka_6rcT-u-X9dXmAYFCDprbtQ',
    appId: '1:330337503528:web:4365cb69884c1acec6281d',
    messagingSenderId: '330337503528',
    projectId: 'commv-users',
    authDomain: 'commv-users.firebaseapp.com',
    storageBucket: 'commv-users.firebasestorage.app',
    measurementId: 'G-W08ZWVTYQK',
  );
}
